# Generated by Django 3.2.8 on 2021-10-16 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('medialogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site', verbose_name='sites'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
